version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: euroasian-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: euroasiangroup_erp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - euroasian-network

  redis:
    image: redis:7-alpine
    container_name: euroasian-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - euroasian-network
    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: euroasian-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/euroasiangroup_erp
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - euroasian-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local

networks:
  euroasian-network:
    driver: bridge

